### ISSUE TITLE
Google Maps JavaScript API error

### ISSUE THREAD

**Issue by JackDougherty** [datamade/searchable-map-template-csv#25]
Your demo map page is throwing a Google Maps JS API error
https://searchable-map-template-csv.netlify.app/

<img width="1118" alt="map-error" src="https://user-images.githubusercontent.com/649719/93120196-ff780280-f690-11ea-9f9c-753f6650f6f9.png">

**Comment by derekeder** [comment]
@JackDougherty thanks for catching this! Looks like Netlify changed their app domain from `netlify.com` to `netlify.app`. I updated the allowed referrer in the Google API console and it is working again.
