### ISSUE TITLE
handle newlines at the end of csv files

### ISSUE THREAD

**Issue by derekeder** [datamade/searchable-map-template-csv#9]
While testing the CSV parsing, I noticed that having newlines at the end of my CSV file caused the map to fail to load. Should add some checks to skip or delete empty rows at the end of CSV files.

**Comment by EvanHahn** [comment]
Is this something you're looking for help on? I might be able to take a look.

**Comment by derekeder** [comment]
@EvanHahn yah that would be great! I'd like to come up with a solution that checks for blank lines when a CSV is parsed here: https://github.com/datamade/searchable-map-template-turf/blob/master/js/searchable_map_lib.js#L127

A PR would be most welcome!

**Comment by EvanHahn** [comment]
I just tried to reproduce this and couldn't get an error when I had one or many blank lines at the end of my CSV file. Is there a way you're able to reproduce this?

This change should theoretically fix the issue, though I wasn't able to reproduce it to test:

```diff
diff --git a/js/searchable_map_lib.js b/js/searchable_map_lib.js
index ef544bd..b3d4da2 100644
--- a/js/searchable_map_lib.js
+++ b/js/searchable_map_lib.js
@@ -124,7 +124,7 @@ var SearchableMapLib = {
         else if (SearchableMapLib.fileType == 'csv' ){
           // convert CSV
           if (SearchableMapLib.debug) console.log('converting to csv');
-          SearchableMapLib.geojsonData = convertCsvToGeojson(data)
+          SearchableMapLib.geojsonData = convertCsvToGeojson($.trim(data))
         }
         else {
           // error!
```

**Comment by derekeder** [comment]
you're right. i wasn't able to reproduce this again either. lets close for now and reopen if it comes up again.
